version: '3.6'

services:
  python:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    command: /bin/sh "/programame/docker/dev/django.sh"
    volumes:
      - ./:/programame:Z
    working_dir: /programame
    tty: true
    ports:
      - 8000:8000
