version: '3.6'

services:
  python:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    command: /bin/sh "/programame/docker/prod/gunicorn.sh"
    volumes:
      - ./:/programame:Z
    working_dir: /programame
    tty: true
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    restart: always
